
#include <cstddef>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <vector>
#include <deque>
#include <list>
#include <map>
#include <set>
#include <cmath>
#include <algorithm>
#include <string>

#include "xtal_utility.h"
#include "xtal_fwd.h"
#include "xtal_allocator.h"
#include "xtal_any.h"
#include "xtal_base.h"
#include "xtal_smartptr.h"
#include "xtal_basictype.h"
#include "xtal_array.h"
#include "xtal_hashtable.h"
#include "xtal_map.h"
#include "xtal_string.h"
#include "xtal_text.h"
#include "xtal_inst.h"
#include "xtal_cast.h"
#include "xtal_code.h"
#include "xtal_stack.h"
#include "xtal_debug.h"
#include "xtal_lib.h"
#include "xtal_vmachine.h"
#include "xtal_cfun.h"
#include "xtal_thread.h"
#include "xtal_frame.h"
#include "xtal_iterator.h"
#include "xtal_thread.h"
#include "xtal_ch.h"
#include "xtal_stream.h"
#include "xtal_smartptr.h"
#include "xtal_except.h"
#include "xtal_proxy.h"
#include "xtal_expr.h"
#include "xtal_parser.h"
#include "xtal_codebuilder.h"
#include "xtal_xeg.h"
#include "xtal_serializer.h"
#include "xtal_fun.h"

