
#pragma once

#include "xtal.h"

#include "xtal_allocator.cpp"
#include "xtal_any.cpp"
#include "xtal_array.cpp"
#include "xtal_base.cpp"
#include "xtal_basic_type.cpp"
#include "xtal_cast.cpp"
#include "xtal_cfun.cpp"
#include "xtal_ch.cpp"
#include "xtal_code.cpp"
#include "xtal_codebuilder.cpp"
#include "xtal_core.cpp"
#include "xtal_debug.cpp"
#include "xtal_except.cpp"
#include "xtal_expr.cpp"
#include "xtal_format.cpp"
#include "xtal_frame.cpp"
#include "xtal_fun.cpp"
#include "xtal_iterator.cpp"
#include "xtal_lib.cpp"
#include "xtal_map.cpp"
#include "xtal_math.cpp"
#include "xtal_parser.cpp"
#include "xtal_peg.cpp"
#include "xtal_serializer.cpp"
#include "xtal_smartptr.cpp"
#include "xtal_stack.cpp"
#include "xtal_stream.cpp"
#include "xtal_string.cpp"
#include "xtal_thread.cpp"
#include "xtal_vmachine.cpp"
